In [ ]:
 import numpy as np

In [ ]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
 list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
 np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
 np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#### linearly spaced(linspace)###

In [ ]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
import numpy as np

In [6]:
np.random.rand(3,2)

array([[0.77511504, 0.93284138],
       [0.91566544, 0.91010707],
       [0.56172878, 0.60602122]])

In [8]:
np.random.randn(3,2)

array([[-0.59236416,  0.94494556],
       [-0.32115339, -1.44744341],
       [ 0.37058623, -0.06758686]])

In [9]:
np.random.randint(34,100)

87

In [10]:
np.random.randint(20,56,100)

array([30, 37, 41, 22, 34, 21, 43, 20, 32, 40, 44, 29, 55, 24, 28, 33, 29,
       45, 37, 30, 40, 47, 20, 54, 42, 41, 25, 54, 55, 44, 28, 40, 45, 50,
       33, 24, 46, 48, 42, 36, 47, 48, 28, 21, 45, 29, 26, 37, 55, 21, 36,
       39, 49, 43, 44, 47, 44, 38, 50, 54, 41, 34, 35, 24, 24, 20, 53, 23,
       49, 22, 43, 21, 43, 43, 36, 27, 38, 48, 32, 49, 50, 28, 38, 33, 29,
       44, 51, 36, 25, 40, 39, 27, 27, 21, 22, 48, 32, 33, 32, 46])

In [11]:
sample_array=np.arange(30)

In [12]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
rand_array=np.random.randint(0,100,20)

In [14]:
rand_array

array([42, 95, 67, 58, 69, 99, 39, 81, 38, 44, 58,  9, 35, 48, 96, 60, 16,
        8, 19, 92])

In [15]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [16]:
sample_array.reshape(3,7)

ValueError: ignored

In [17]:
rand_array.min()

8

In [18]:
rand_array.max()

99

In [19]:
sample_array.dtype

dtype('int64')

In [20]:
sample_array [3:7]

array([3, 4, 5, 6])

In [22]:
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [23]:
sample_array[1:4]=100

In [24]:
sampe_array

NameError: ignored

In [25]:
sample_array

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [26]:
####### TWO DIMENSIONAL ARRAY#####

In [27]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix


array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [29]:
sample_matrix[0][2]

1

In [30]:
sample_matrix[1][2]

21

In [31]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [32]:
sample_matrix[2]

array([56, 76, 24,  7])

In [4]:
###### SELECTION TECHNIQUES#####

In [6]:
import numpy as np


In [7]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [9]:
np.exp(sample_array) ##exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [10]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [11]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [12]:
np.max(sample_array)

19

In [13]:
np.min(sample_array)

1

In [14]:
np.argmax(sample_array)

18

In [15]:
np.argmin(sample_array)

0

In [16]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [17]:
np.std(sample_array)

5.477225575051661

In [18]:
np.var(sample_array)

30.0

In [19]:
np.mean(sample_array)

10.0

In [20]:
array=np.random.randn(3,4)
array

array([[ 0.03234979,  0.33289288,  0.98141669, -1.3682601 ],
       [-0.0675409 ,  1.04424775,  0.55128729,  1.05349764],
       [ 1.59482902, -0.78123824, -0.77067152, -0.33174277]])

In [21]:
np.round(array,decimals=4)

array([[ 0.0323,  0.3329,  0.9814, -1.3683],
       [-0.0675,  1.0442,  0.5513,  1.0535],
       [ 1.5948, -0.7812, -0.7707, -0.3317]])

In [23]:
np.round(array,decimals=1)

array([[ 0. ,  0.3,  1. , -1.4],
       [-0.1,  1. ,  0.6,  1.1],
       [ 1.6, -0.8, -0.8, -0.3]])

In [24]:
sports=np.array(['golf','cricket','fball','cricket','football'])
np.unique(sports)

array(['cricket', 'fball', 'football', 'golf'], dtype='<U8')

In [ ]:
###pandas->To create data,create data,create table,manipulation